all:
  children:
    dhcp_servers:
      vars:
        ansible_user: root
      hosts:
        cnv-dhcp1.massopen.cloud:
          dhcp_role: primary
        cnv-dhcp2.massopen.cloud:
          dhcp_role: secondary
