dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: dhcp1
    image: "${MOLECULE_IMAGE:-quay.io/fedora/fedora:34}"
    pre_build_image: true
    groups:
      - dhcp_servers
  - name: dhcp2
    image: "${MOLECULE_IMAGE:-quay.io/fedora/fedora:34}"
    pre_build_image: true
    groups:
      - dhcp_servers
provisioner:
  name: ansible
  inventory:
    group_vars:
      dhcp_servers:
        manage_services: false
        dnsmasq_listen_addresses:
          - 1.2.3.4
    host_vars:
      dhcp1:
        dhcp_role: primary
      dhcp2:
        dhcp_role: secondary
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
